global_costmap:
  global_frame: /map
  robot_base_frame: base_frame
  update_frequency: 5.0
  publish_frequency: 2.0
  static_map: true
  transform_tolerance: 3.0
  obstacle_range: 3.0
  raytrace_range: 3.5
  footprint: '[]'
  robot_radius: 0.20
  inflation_radius: 0.10
  cost_scaling_factor: 5.0

  observation_sources: laser_scan_sensor 
  laser_scan_sensor: {sensor_frame: laser_frame, data_type: LaserScan, topic: scan, marking: true, clearing: true}

  inflation_layer:
    enabled: true
    cost_scaling_factor: 5.0
    inflate_unknown: false
    inflation_radius: 0.1

  obstacle_layer:
    enabled: true
    combination_method: 1
    footprint_clearing_enabled: false
    max_obstacle_height: 2.0
    obstacle_range: 3.0
    raytrace_range: 3.5

