controller_frequency:  5.0
controller_patience:  60.0
planner_patience:  60.0
#oscillation_timeout: 30.0
#oscillation_distance: 0.5

footprint_padding: 0.01
clearing_rotation_allowed: true
clearing_radius: 0.2

base_global_planner: navfn/NavfnROS
base_local_planner: base_local_planner/TrajectoryPlannerROS

NavfnROS:
  allow_unknown: true

TrajectoryPlannerROS:
  max_vel_x: 0.3
  min_vel_x: 0.0
  max_rotational_vel: 0.5
  min_in_place_rotational_vel: 0.4

  acc_lim_th: 0.5
  acc_lim_x: 0.3 #maximum is 2.0
  acc_lim_y: 0.0 #diff drive robot

  holonomic_robot: false

  yaw_goal_tolerance: 0.3
  xy_goal_tolerance: 0.2
  latch_xy_goal_tolerance: true

  dwa: false

  heading_lookahead: 0.5

  publish_cost_grid_pc: false

  pdist_scale: 0.6
  gdist_scale: 0.8
  occdist_scale: 0.5

  oscillation_reset_dist: 0.05


